# -*- coding: utf-8 -*-
"""Formula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhCI72wH32ZhdYLKLYkFcs_eDGV-GY31
"""

import pandas as pd
import matplotlib.pyplot as plt

#/content/F1Drivers_Dataset.csv
df=pd.read_csv('//content/F1Drivers_Dataset.csv')
data=pd.DataFrame(df)
print(data)

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

"""✈**//Consultas que se desean realizar**

***1- Filtrar los datos para los años entre 2000 y 2022***
"""

filtered_df = df[df['Seasons'].apply(lambda x: any(year in range(2000, 2023) for year in x))]

# Encontrar el piloto con más victorias
max_wins_pilot = filtered_df.loc[filtered_df['Race_Wins'].idxmax()]

# Mostrar el resultado
print("Piloto con más victorias entre 2000 y 2022:")
print(f"Nombre: {max_wins_pilot['Driver']}")
print(f"Victorias: {max_wins_pilot['Race_Wins']}")

"""
**2-Top 10 pilotos con más participación en carreras entre 1954 y 2022**


"""

# Convertir la columna 'Seasons' de cadenas a listas
df['Seasons'] = df['Seasons'].apply(lambda x: eval(x) if isinstance(x, str) else x)

# Filtrar los datos para los años entre 1954 y 2022
filtered_df = df[df['Seasons'].apply(lambda x: any(year in range(1954, 2023) for year in x))]

# Ordenar por el número de participaciones en carreras y seleccionar los 10 primeros
top_10_pilots = filtered_df.nlargest(10, 'Race_Entries')

# Mostrar el resultado
print("Top 10 pilotos con más participación en carreras entre 1954 y 2022:")
print(top_10_pilots[['Driver', 'Race_Entries']])

"""**3- Top 10 pilotos con más participación en carreras entre 1954 y 2022**"""

datafiltered = df.sort_values('Podiums', ascending=False)  # busca ascendentemente los podios de los pilotos.

# Selecciona el top 10 de los pilotos
top_10 = datafiltered.head(10)

# imprime el resultado
print(top_10[['Driver', 'Podiums']])

"""***4- Piloto italiano con mas carreras ganadas***"""

# Filtrar por país Italia
italian_drivers = df[df['Nationality'] == 'Italy']

# Encontrar el piloto con más victorias
top_italian_driver = italian_drivers.loc[italian_drivers['Race_Wins'].idxmax()]

# Mostrar el resultado
print("Piloto italiano con más victorias en carreras:")
print(f"Nombre: {top_italian_driver['Driver']}")
print(f"Victorias: {top_italian_driver['Race_Wins']}")

"""***5- top 10 pilotos con mas carreras ganadas de 1954 a 2022`*`**"""

filtered_df = df[df['Seasons'].apply(lambda x: any(year in range(1954, 2022) for year in x))]

# Ordenar por el número de participaciones en carreras y seleccionar los 10 primeros
top_10_pilots = filtered_df.nlargest(10, 'Race_Wins')

# Mostrar el resultado
print("Top 10 pilotos con más victorias en carreras entre 1954 y 2022:")
print(top_10_pilots[['Driver', 'Race_Wins']])